services:
  mongo:
    image: mongo:7
 
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: loginjwt
 
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]  
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo

    depends_on:
      - mongo

volumes:
  mongo_data:
